name: Laravel CI (MySQL)

on:
  push:          { branches: [main] }
  pull_request:  { branches: [main] }

jobs:
  tests:
    runs-on: ubuntu-latest

    # ────────────────────────────────
    # 1) Servicio MySQL 8
    # ────────────────────────────────
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ci_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports: [3306:3306]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3   # espera a que el contenedor esté “healthy”

    # Variables disponibles en todos los pasos
    env:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: ci_test
      DB_USERNAME: laravel
      DB_PASSWORD: secret

    steps:
    # 2) Código fuente
    - uses: actions/checkout@v4                                         # :contentReference[oaicite:0]{index=0}

    # 3) PHP 8.2 + extensiones
    - uses: shivammathur/setup-php@v2                                   
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo_mysql                         # :contentReference[oaicite:1]{index=1}

    # 4) Dependencias Composer
    - name: Instalar dependencias
      run: composer install --prefer-dist --no-interaction --no-progress  # :contentReference[oaicite:2]{index=2}

    # 5) Preparar entorno
    - run: cp .env.example .env
    - run: php artisan key:generate                                      # :contentReference[oaicite:3]{index=3}

    # 6) Esperar a MySQL (por si el health‑check tarda)
    - name: Esperar MySQL
      run: |
        until mysql -h 127.0.0.1 -ularavel -psecret -e "SELECT 1"; do
          sleep 1
        done                                                             # :contentReference[oaicite:4]{index=4}

    # 7) Migraciones + seeders
    - run: php artisan migrate --seed --no-interaction                   # :contentReference[oaicite:5]{index=5}

    # 8) Tests (sin --parallel ⇒ no necesita ParaTest)
    - name: Ejecutar tests
      run: php artisan test
